module Types where

import Graphics.Gloss.Interface.Pure.Game

data Images = Images {
  image1         :: Picture,
  image2         :: Picture,
  image3         :: Picture,
  image4         :: Picture,
  image5         :: Picture,

  image11         :: Picture,
  image12         :: Picture,
  image13         :: Picture,
  image14         :: Picture,
  image15         :: Picture,
  image16         :: Picture,
  image17         :: Picture,
  image18         :: Picture,

  image21         :: Picture,
  image22         :: Picture,
  image23         :: Picture,
  image24         :: Picture,
  image25         :: Picture,
  image26         :: Picture,
  image27         :: Picture,
  image28         :: Picture,
  image29         :: Picture,
  image30         :: Picture,

  image31         :: Picture,
  image32         :: Picture,
  image33         :: Picture,
  image34         :: Picture,
  image35         :: Picture,
  image36         :: Picture,
  image37         :: Picture,
  image38         :: Picture,
  image39         :: Picture,
  image40         :: Picture,

  image41         :: Picture,
  image42         :: Picture,
  image43         :: Picture,
  image44         :: Picture,
  image45         :: Picture,
  image46         :: Picture,
  image47         :: Picture,
  image48         :: Picture,


  p2image1         :: Picture,
  p2image2         :: Picture,
  p2image3         :: Picture,
  p2image4         :: Picture,
  p2image5         :: Picture,

  p2image11         :: Picture,
  p2image12         :: Picture,
  p2image13         :: Picture,
  p2image14         :: Picture,
  p2image15         :: Picture,
  p2image16         :: Picture,
  p2image17         :: Picture,
  p2image18         :: Picture,

  p2image21         :: Picture,
  p2image22         :: Picture,
  p2image23         :: Picture,
  p2image24         :: Picture,
  p2image25         :: Picture,
  p2image26         :: Picture,
  p2image27         :: Picture,
  p2image28         :: Picture,
  p2image29         :: Picture,
  p2image30         :: Picture,

  p2image31         :: Picture,
  p2image32         :: Picture,
  p2image33         :: Picture,
  p2image34         :: Picture,
  p2image35         :: Picture,
  p2image36         :: Picture,
  p2image37         :: Picture,
  p2image38         :: Picture,
  p2image39         :: Picture,
  p2image40         :: Picture,

  p2image41         :: Picture,
  p2image42         :: Picture,
  p2image43         :: Picture,
  p2image44         :: Picture,
  p2image45         :: Picture,
  p2image46         :: Picture,
  p2image47         :: Picture,
  p2image48         :: Picture
}